### PR TITLE
Sohail/remove google auth

### PR DESCRIPTION
**Pull request by SohailSayed**
## Notion Ticket Link

[Remove Google Auth for Login](https://www.notion.so/uwblueprintexecs/Remove-Google-Auth-for-Login-f7520a768f8b402e830e9ab8cce0a27a?pvs=4)

## Implementation Description
* Removed ability to login with Google Auth. Removed google auth related functions/types

## Steps to Test
1. Test signing up, ensure you receive a verification email (use 'youremail+[anythingyouwant]@uwblueprint.org' eg. 'sohailsayed+1@uwblueprint.org' to signup multiple times w the same email)
2. Test logging in once signed up and verified

## Screenshots (optional)
image
Google sign-in option should be gone.

## Checklist
- [x ] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### Mac
```bash
docker exec -it CWC-backend /bin/bash -c "yarn fix"
docker exec -it CWC-frontend /bin/bash -c "yarn fix"
```

### Windows
```bash
docker exec -it CWC-backend bash -c "yarn fix"
docker exec -it CWC-frontend bash -c "yarn fix"
```

### CODE REVIEW

**Review by carolynzhang18 — CHANGES_REQUESTED** [review]
Everything looks good!! 🔥 Just remove `react-google-login` and it's good to go :D Good job!

**Review by itsjanevvu — APPROVED** [review]
Looks good!

**Review by carolynzhang18 — APPROVED** [review]
woooo!! 😎

**Comment by SohailSayed** [comment]
> woooo!! 😎
> 
> looks like there's some fun merge conflicts coming your way too 😶‍🌫️

Thanks. Yay merge conflicts! 💀

**Review by owen-sellner — APPROVED** [review]
LGTM!!! Good job, this is ready to merge 🥳

**Pull request merged**
